name: Auto Merge PR Publish

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  merge-pr-package:
    if: contains(github.event.pull_request.labels.*.name, 'bump-version')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GH_BOT_MERGE_TOKEN }}

      - name: Force Merge PR
        run: gh pr merge "$PR_NUMBER" --squash --admin
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_MERGE_TOKEN }}

